preprocess:
  input: data/raw/winequality.csv
  output: data/processed/winequality.csv
  y_test_reg: data/processed/y_test_reg.csv
  y_test_clf: data/processed/y_test_clf.csv
  X_test_reg: data/processed/y_test_reg.csv
  X_test_clf: data/processed/y_test_clf.csv
 
 

train:
  X_train_reg: data/for_training/X_train_reg.csv
  y_train_reg: data/for_training//y_train_reg.csv
  X_train_clf: data/for_training//X_train_clf.csv
  y_train_clf: data/for_training//y_train_clf.csv

  model_1_reg: models/model_1_reg.pkl
  model_1_clf: models/model_1_clf.pkl

  model_2_reg: models/model_2_reg.pkl
  model_2_clf: models/model_2_clf.pkl

evalution:
  y_test_reg: data/for_evalution/y_test_reg.csv
  y_test_clf: data/for_evalution/y_test_clf.csv
  X_test_reg: data/for_evalution/X_test_reg.csv
  X_test_clf: data/for_evalution/X_test_clf.csv

mlflow:
  uri: "http://127.0.0.1:5000"


